In [1]:
import pandas as pd
import numpy as np

In [76]:
data = {"feature1" : [1 , 2 ,3 ,4 , 5 , 6] , "feature2":[2,4,5,6,7,8] , "class":[0,1,0,1,0,0]}

In [77]:
data = pd.DataFrame(data)

##### data

In [79]:
for i in range(data.shape[-1]-1):
    data.iloc[:,i] = np.where(data['class'] == 0  ,  -data.iloc[:,i] , data.iloc[:,i])

In [80]:
data

feature1  feature2  class
0        -1        -2      0
1         2         4      1
2        -3        -5      0
3         4         6      1
4        -5        -7      0
5        -6        -8      0

In [102]:
data.shape

(6, 3)

In [115]:
def linear_classifier(data):
    a = data.shape[-1]
    weights = np.random.randn(1 , a)
    labels = data.iloc[:,-1]
    data = data.drop(labels = "class" , axis = 1)
    arr = np.ones((data.shape[0],1))
    data = np.hstack((arr , data.values))
    learning_rate = 0.01
    print("Before  : ", weights)
    for k in range(1000):
        output =  weights @ data.T
        vector = np.zeros(a)
        for i , j in enumerate(output[0]):
            if j < 0 :
                vector += arr[i , :]
        weights += learning_rate*vector
    return weights

In [116]:
weights = linear_classifier(data)

Before  :  [[ 1.44373836  0.49232771 -0.40456431]]


In [117]:
weights

array([[ 1.44373836,  0.49232771, -0.40456431]])

In [118]:
data1 = data.drop(labels = "class" , axis = 1)
arr = np.ones((data.shape[0],1))
data1 = np.hstack((arr , data1.values))
output =  weights @ data1.T

In [119]:
output

array([[1.76053927, 0.81013654, 1.98957678, 0.98566334, 1.81404999,
        1.72628659]])

In [103]:
np.random.randn(1,2)

array([[-0.72705796,  0.72760257]])

In [104]:
data1

array([[ 1., -1., -2.],
       [ 1.,  2.,  4.],
       [ 1., -3., -5.],
       [ 1.,  4.,  6.],
       [ 1., -5., -7.],
       [ 1., -6., -8.]])